/**
 * Frozen copies of every memory block this server has ever served WITHOUT the
 * `cxx:managed-features` markers.
 *
 * Why these are literals and not regenerated: `stripManagedContent` removes a
 * previously served copy that an operator pasted back into the canonical
 * document. Inside the markers `OWN_BLOCK` handles that by position, so content
 * does not matter. But between 2026-07-27 (79bb06d6, which wired
 * `appendManagedMemoryBlock` into HostAgentsService) and 2026-07-30 (511f5673,
 * which replaced it with the marker-delimited renderer) the block was appended
 * raw, under its undemoted `## Memory (managed)` heading. Those bytes are still
 * sitting in any canonical document edited during that window.
 *
 * Regenerating from the current renderer would silently stop matching them, and
 * the served document would then carry the stale doctrine beside the current
 * one. Since the whole point of the current block is telling agents not to leave
 * a corrected fact next to a stale one, shipping exactly that bug would be
 * unfortunate.
 *
 * Rules: append on every text change, never prune, never hand-edit. These are
 * exact rendered bytes, JSON-escaped so no template-literal escaping can corrupt
 * them. Fragments are NOT allowed here — the strip is a plain substring removal,
 * so a partial entry would gut the middle of an old block and orphan the rest.
 */
export const HISTORIC_MANAGED_MEMORY_BLOCKS: readonly string[] = [
  // 79bb06d6 / codex — 2026-07-27 15:56, the first TS-era block
  "## Memory (managed)\n\nDurable memory lives in the orchestrator over MCP, not in local files. Local scratch files under the Codex home (and any ad-hoc notes file) are host-local. Do not use them for anything durable or shared, and do not mirror orchestrator memory into them.\n\nThree stores, and they are not interchangeable:\n\n- `shared_memory_*` \u2014 **fleet-wide documents**. Runbooks, architecture notes, accumulated findings:\n  anything the next agent on a different host or a different project would want. Not scoped to a host\n  or a project. Start with `shared_memory_list` (it needs no query) to see what the fleet already\n  knows, narrow with `shared_memory_search`, read with `shared_memory_read`. Add to an existing\n  document with `shared_memory_append` rather than read-modify-write \u2014 other agents write here too.\n- `project_memory_*` \u2014 short facts about one workstream, keyed `<area>.<topic>`. Needs a project\n  slug. Enumerate with `project_memory_list`.\n- `memory_*` \u2014 host-local scratch, tied to this machine. It cannot be listed, so nobody else can\n  discover what it holds. Never use it for anything another agent needs.\n\nWhen work will outlive this session, check `shared_memory_list` before starting and record what you\nlearned before finishing. Never store secrets \u2014 keys, tokens, credentials, customer data \u2014 in any of\nthem.\n",
  // 79bb06d6 / claude — 2026-07-27 15:56, the first TS-era block
  "## Memory (managed)\n\nDurable memory lives in the orchestrator over MCP, not in local files. Claude Code's built-in file memory (`~/.claude/projects/**/memory/*.md` and its `MEMORY.md` index) is host-local. Do not use it for anything durable or shared, and do not mirror orchestrator memory into it. Use it only for notes that are genuinely about this one machine.\n\nThree stores, and they are not interchangeable:\n\n- `shared_memory_*` \u2014 **fleet-wide documents**. Runbooks, architecture notes, accumulated findings:\n  anything the next agent on a different host or a different project would want. Not scoped to a host\n  or a project. Start with `shared_memory_list` (it needs no query) to see what the fleet already\n  knows, narrow with `shared_memory_search`, read with `shared_memory_read`. Add to an existing\n  document with `shared_memory_append` rather than read-modify-write \u2014 other agents write here too.\n- `project_memory_*` \u2014 short facts about one workstream, keyed `<area>.<topic>`. Needs a project\n  slug. Enumerate with `project_memory_list`.\n- `memory_*` \u2014 host-local scratch, tied to this machine. It cannot be listed, so nobody else can\n  discover what it holds. Never use it for anything another agent needs.\n\nWhen work will outlive this session, check `shared_memory_list` before starting and record what you\nlearned before finishing. Never store secrets \u2014 keys, tokens, credentials, customer data \u2014 in any of\nthem.\n",
  // 4ba25984 / codex — 2026-07-27 16:31, the lookup-first rewrite
  "## Memory (managed)\n\nThis fleet keeps what it knows in the orchestrator, reachable over MCP. It is shared across every\nhost and both engines, and it is authoritative over your own assumptions.\n\n**Looking something up.** If you are asked about this fleet, a host, a convention, a runbook, or any\npast decision \u2014 and you do not already know the answer \u2014 call `shared_memory_list` (it takes no\narguments) or `shared_memory_search` **first, before searching the filesystem**. Read the hit with\n`shared_memory_read`. Saying \"I could not find it\" without having checked there is a wrong answer:\nthat is where the answer lives. `memory_*` is host-local scratch and is NOT a lookup surface \u2014\nit cannot be listed, so it can never tell you what exists.\n\n**Writing something down.** Anything the next agent \u2014 on another host, in another session \u2014 would\nwant belongs in `shared_memory_write`, or `shared_memory_append` to add to a document that\nalready exists. Facts about one workstream go in `project_memory_*`. Codex's own local memories feature and any ad-hoc notes file under the Codex home are host-local: another host and a reinstalled workstation cannot see them. Do not use them for anything durable or shared, and do not mirror orchestrator memory into them.\n\nNever store secrets \u2014 keys, tokens, credentials, customer data \u2014 in any of them.\n",
  // 4ba25984 / claude — 2026-07-27 16:31, the lookup-first rewrite
  "## Memory (managed)\n\nThis fleet keeps what it knows in the orchestrator, reachable over MCP. It is shared across every\nhost and both engines, and it is authoritative over your own assumptions.\n\n**Looking something up.** If you are asked about this fleet, a host, a convention, a runbook, or any\npast decision \u2014 and you do not already know the answer \u2014 call `shared_memory_list` (it takes no\narguments) or `shared_memory_search` **first, before searching the filesystem**. Read the hit with\n`shared_memory_read`. Saying \"I could not find it\" without having checked there is a wrong answer:\nthat is where the answer lives. `memory_*` is host-local scratch and is NOT a lookup surface \u2014\nit cannot be listed, so it can never tell you what exists.\n\n**Writing something down.** Anything the next agent \u2014 on another host, in another session \u2014 would\nwant belongs in `shared_memory_write`, or `shared_memory_append` to add to a document that\nalready exists. Facts about one workstream go in `project_memory_*`. Claude Code's built-in file memory (`~/.claude/projects/**/memory/*.md` and its `MEMORY.md` index) is host-local: another host and a reinstalled workstation cannot see it. Do not use it for anything durable or shared, and do not mirror orchestrator memory into it.\n\nNever store secrets \u2014 keys, tokens, credentials, customer data \u2014 in any of them.\n",
];
