import { describe, it, expect } from 'vitest';
import { check } from '../../../src/security/phpass.js';

/**
 * The two vectors below were produced by Openwall's phpass PortableHash under
 * PHP 8.4 (`crypt_private()`), not by running this module — they are the
 * external reference the port has to reproduce. `$P$5…` uses the lowest legal
 * iteration count (itoa64['5'] = 7 → 128 rounds), `$H$9…` the alternate prefix
 * WordPress-era installs also emit (itoa64['9'] = 11 → 2048 rounds).
 */
const P_HASH = '$P$5rBqxLmb2ljJA8u.iIJRENtee4sOhJ.';
const P_PASSWORD = 'correct horse battery staple';

const H_HASH = '$H$9saltysalZFMKYAnKVZNFLi/ppY7Mm/';
const H_PASSWORD = 'hunter2';

describe('phpass.check', () => {
  it('accepts a $P$ vector generated by PHP phpass', () => {
    expect(check(P_PASSWORD, P_HASH)).toBe(true);
  });

  it('accepts a $H$ vector generated by PHP phpass', () => {
    expect(check(H_PASSWORD, H_HASH)).toBe(true);
  });

  it('rejects the wrong password for both vectors', () => {
    expect(check('wrong password', P_HASH)).toBe(false);
    expect(check(P_PASSWORD + ' ', P_HASH)).toBe(false);
    expect(check('', P_HASH)).toBe(false);
    expect(check('hunter3', H_HASH)).toBe(false);
  });

  it('rejects a hash whose salt has been tampered with', () => {
    // salt occupies [4, 12); flip its first character
    const tampered = P_HASH.slice(0, 4) + 's' + P_HASH.slice(5);
    expect(tampered).not.toBe(P_HASH);
    expect(check(P_PASSWORD, tampered)).toBe(false);
  });

  it('rejects a hash whose final encoded character has been tampered with', () => {
    const tampered = P_HASH.slice(0, -1) + '/';
    expect(tampered).not.toBe(P_HASH);
    expect(check(P_PASSWORD, tampered)).toBe(false);
  });

  it('rejects a non-phpass prefix', () => {
    expect(check(P_PASSWORD, '$Q$' + P_HASH.slice(3))).toBe(false);
    expect(check(P_PASSWORD, 'P$$' + P_HASH.slice(3))).toBe(false);
  });

  it('rejects a stored string shorter than 12 characters', () => {
    expect(check(P_PASSWORD, P_HASH.slice(0, 11))).toBe(false);
    expect(check(P_PASSWORD, '$P$')).toBe(false);
    expect(check(P_PASSWORD, '')).toBe(false);
  });

  it('rejects an iteration count outside the 7..30 itoa64 range', () => {
    // itoa64['.'] = 0 (below the floor), itoa64['T'] = 31 (above the ceiling)
    expect(check(P_PASSWORD, '$P$.' + P_HASH.slice(4))).toBe(false);
    expect(check(P_PASSWORD, '$P$T' + P_HASH.slice(4))).toBe(false);
    // a character absent from itoa64 indexes as -1
    expect(check(P_PASSWORD, '$P$!' + P_HASH.slice(4))).toBe(false);
  });

  it('rejects a truncated digest of the right prefix', () => {
    expect(check(P_PASSWORD, P_HASH.slice(0, 33))).toBe(false);
    expect(check(P_PASSWORD, P_HASH + '.')).toBe(false);
  });
});
