<?php

declare(strict_types=1);

namespace App\Services\Wrapper\V2;

use App\Support\Engine;

/**
 * BootstrapShimBuilder emits the tiny POSIX `sh` script the host runs every
 * invocation. The shim:
 *   1. Fetches a fresh signed config from the orchestrator.
 *   2. Downloads the engine binary if SHA256 disagrees.
 *   3. Execs the binary with --config <local path>.
 *
 * Everything that requires structured data lives inside the binary; the shim
 * is intentionally dumb so it survives platform variations.
 */
final class BootstrapShimBuilder
{
    /**
     * @param string $engine             Engine::CODEX | Engine::CLAUDE
     * @param string $baseUrl            Public orchestrator base URL.
     * @param string $hostApiKey         Per-host API key, sent as X-API-Key.
     */
    public static function build(string $engine, string $baseUrl, string $hostApiKey): string
    {
        $engine = Engine::isValid($engine) ? $engine : Engine::CODEX;
        $name = Engine::WRAPPER_NAME[$engine];          // cdx | clx
        $envPrefix = strtoupper($name);                  // CDX | CLX
        $base = rtrim($baseUrl, '/');

        $configUrl = $base . '/wrapper/v2/config?engine=' . $engine;
        $apiKey = self::shellQuote($hostApiKey);
        $configUrlQ = self::shellQuote($configUrl);
        $sigUrlQ = self::shellQuote($configUrl . '&sig=1');
        $binPathBase = self::shellQuote($base . '/wrapper/v2/bin/' . $engine);

        return <<<SH
#!/bin/sh
# wrapper-v2 bootstrap shim for {$name}
# Generated by the orchestrator. Do not edit; regenerated on every install.
set -eu

HOST_API_KEY={$apiKey}
{$envPrefix}_HOME=\${{$envPrefix}_HOME:-\$HOME/.config/codex-orchestrator}
BIN_DIR=\${BIN_DIR:-\$HOME/.local/bin}
mkdir -p "\$BIN_DIR" "\${{$envPrefix}_HOME}"

CFG="\${{$envPrefix}_HOME}/{$name}.json"
SIG="\${{$envPrefix}_HOME}/{$name}.json.sig"

# 1. Fetch signed config.
curl -fsSL -H "X-API-Key: \$HOST_API_KEY" -o "\$CFG.new" {$configUrlQ}
curl -fsSL -H "X-API-Key: \$HOST_API_KEY" -o "\$SIG.new" {$sigUrlQ}
mv "\$CFG.new" "\$CFG"
mv "\$SIG.new" "\$SIG"

# 2. Resolve platform.
OS=\$(uname -s | tr '[:upper:]' '[:lower:]')
ARCH=\$(uname -m); case "\$ARCH" in
  x86_64|amd64) ARCH=amd64;;
  aarch64|arm64) ARCH=arm64;;
esac

# 3. Pull expected SHA256 + binary URL from the signed config. Prefer jq; fall
# back to a python3 one-liner; finally to sed-based extraction.
sha=""
if command -v jq >/dev/null 2>&1; then
  sha=\$(jq -r .wrapper.binary_sha256 < "\$CFG" 2>/dev/null || true)
  url=\$(jq -r .wrapper.binary_url     < "\$CFG" 2>/dev/null || true)
elif command -v python3 >/dev/null 2>&1; then
  sha=\$(python3 -c 'import json,sys;print(json.load(sys.stdin)["wrapper"]["binary_sha256"])' < "\$CFG" 2>/dev/null || true)
  url=\$(python3 -c 'import json,sys;print(json.load(sys.stdin)["wrapper"]["binary_url"])'     < "\$CFG" 2>/dev/null || true)
else
  sha=\$(sed -n 's/.*"binary_sha256"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' "\$CFG")
  url=\$(sed -n 's/.*"binary_url"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' "\$CFG")
fi

# Build a platform-specific URL if the config one is for the canonical linux-amd64.
case "\$url" in
  *"linux-amd64"*)
    url=\${binPathBase}/\$OS-\$ARCH/\$(echo "\$url" | sed -n 's#.*linux-amd64/\(v[^/]*\)/.*#\1#p')/{$name}
    ;;
esac

cur_sha=\$(sha256sum "\$BIN_DIR/{$name}" 2>/dev/null | cut -d' ' -f1 || true)
if [ "\$sha" != "" ] && [ "\$sha" != "\$cur_sha" ]; then
  curl -fsSL -H "X-API-Key: \$HOST_API_KEY" -o "\$BIN_DIR/{$name}.new" "\$url"
  chmod +x "\$BIN_DIR/{$name}.new"
  mv "\$BIN_DIR/{$name}.new" "\$BIN_DIR/{$name}"
fi

# 4. Exec the binary with the freshly-fetched config.
exec "\$BIN_DIR/{$name}" --config "\$CFG" "\$@"
SH;
    }

    private static function shellQuote(string $value): string
    {
        return "'" . str_replace("'", "'\\''", $value) . "'";
    }
}
