import { expect, test, type Page } from '@playwright/test';
const stamp='2026-10-09T09:00:00Z';
async function fixture(page:Page, manage=true) {
 const writes:Array<{path:string;body:unknown}>=[];
 const worktree={worktree_id:'work1',worktree_path:'/work/repo/feature',username:'Beate',engine:'codex',branch:'feature',target_branch:'main',head_sha:'123abc',task:'Improve settings',declared_paths:['frontend/page.svelte'],agent_address_bound:true,heartbeat_at:stamp,expires_at:stamp};
 const lease={request_id:'merge1',worktree_id:'work1',target_branch:'main',verdict:'wait',decided_by:'policy',reason:'Another worker holds the lease',overlap:['frontend/page.svelte'],lease_expires_at:stamp,requested_at:stamp};
 const clone={clone_id:'clone1',host_id:1,fqdn:'host.example',repo_root:'/work/repo',remote_url:'ssh://git.example/repo.git',remote_key:'remote',last_seen_at:stamp,worktrees:[worktree],leases:[lease],recent:[{...lease,request_id:'past1',verdict:'deny',reason:'Paths overlap',model:'test-arbiter',completed_at:stamp}],stale:[{...worktree,worktree_id:'old1',username:'Former worker',status:'abandoned',last_seen_at:stamp,released_at:stamp}]};
 await page.route('**/admin/**',route=>{
  const req=route.request();if(!req.headers().accept?.includes('application/json'))return route.continue();
  const path=new URL(req.url()).pathname;
  const json=(body:unknown,status=200)=>route.fulfill({json:body,status});
  if(path==='/admin/auth/status')return json({authenticated:true,enforced:true,user:{id:1,username:'operator',roles:['owner']},capabilities:['admin.read','git_director.read',...(manage?['git_director.manage']:[])]});
  if(path==='/admin/setup/status')return json({setup_complete:true,critical_complete:true,checks:[],next_actions:[],wizard:{completed_at:stamp,dismissed_at:null}});
  if(path==='/admin/ws/info')return json({enabled:false});
  if(path==='/admin/git-director/state')return json({enabled:true,model:'test',clones:1,worktrees:1,updated_at:stamp});
  if(path==='/admin/git-director/commit-settings')return json({message_style:'short',ai_attribution:false});
  if(path==='/admin/git-director')return json({clones:[clone]});
  if(req.method()==='POST') {writes.push({path,body:req.postDataJSON()});if(path.endsWith('/release'))clone.worktrees=[];if(path.endsWith('/decide')){lease.verdict=req.postDataJSON().verdict;}return json(path.endsWith('/decide')?lease:{});}
  return json({});
 });
 return writes;
}
test('Settings first, linked tabs, search, details and operator decisions',async({page})=>{
 test.setTimeout(60_000);
 const writes=await fixture(page);
 await page.goto('/admin/git-director');
 await expect(page.getByRole('tab',{name:'Settings',exact:true})).toHaveAttribute('aria-selected','true');
 await expect(page.getByLabel('Message length')).toBeVisible();
 await expect(page.getByText('Improve settings',{exact:true})).not.toBeVisible();
 await page.screenshot({path:'/tmp/git-director-settings-desktop.png',animations:'disabled'});
 await page.getByRole('tab',{name:'Activity',exact:true}).click();
 await expect(page).toHaveURL(/tab=activity/);
 const search=page.getByLabel('Search Git Director');
 await search.fill('missing');await expect(page.getByText('No matching results.')).toBeVisible();
 await search.fill('Beate');
 await page.getByRole('button',{name:/Beate · codex/}).click();
 await expect(page.getByRole('dialog')).toContainText('/work/repo/feature');
 await expect(page.getByRole('dialog')).toContainText('frontend/page.svelte');
 await page.keyboard.press('Escape');
 await search.fill('');
 await page.getByRole('tab',{name:'Merge requests',exact:true}).click();
 await page.reload();
 await expect(page.getByRole('tab',{name:'Merge requests',exact:true})).toHaveAttribute('aria-selected','true');
 await expect(page.getByRole('button',{name:'Force allow',exact:true})).toHaveCount(0);
 await page.getByRole('button',{name:/wait main Another worker/}).click();
 await expect(page.getByRole('dialog')).toContainText('frontend/page.svelte');
 await page.getByRole('button',{name:'Force allow',exact:true}).click();
 await expect(page.getByRole('dialog')).not.toBeVisible();
 expect(writes[0]).toEqual({path:'/admin/git-director/requests/merge1/decide',body:{verdict:'allow'}});
 await page.getByRole('button',{name:/allow main Another worker/}).click();
 await page.getByRole('button',{name:'Deny',exact:true}).click();
 await expect(page.getByRole('dialog')).not.toBeVisible();
 expect(writes[1].body).toEqual({verdict:'deny'});
 await page.getByRole('tab',{name:'History',exact:true}).click();
 await page.getByRole('button',{name:/deny main/}).click();
 await expect(page.getByRole('dialog')).toContainText('Paths overlap');
 await expect(page.getByRole('dialog')).toContainText('test-arbiter');
 await expect(page.getByRole('button',{name:'Force allow',exact:true})).toHaveCount(0);
 await page.keyboard.press('Escape');
 await page.getByRole('button',{name:/Session ended Former worker/}).click();
 await expect(page.getByRole('dialog')).toContainText('abandoned');
 await page.keyboard.press('Escape');
 await page.getByRole('tab',{name:'Activity',exact:true}).click();
 await page.getByRole('button',{name:/Beate · codex/}).click();
 await page.getByRole('button',{name:'Release registration',exact:true}).click();
 await expect(page.getByRole('dialog')).not.toBeVisible();
 await expect(page.getByText('No active worktrees.')).toBeVisible();
 expect(writes[2].path).toBe('/admin/git-director/worktrees/work1/release');
});
test('mobile tabs, read-only details, fallback tab and empty states',async({page})=>{
 await page.setViewportSize({width:390,height:844});
 await fixture(page,false);
 await page.goto('/admin/git-director?tab=unknown');
 await expect(page.getByRole('tab',{name:'Settings',exact:true})).toHaveAttribute('aria-selected','true');
 await expect(page.getByLabel('Message length')).toBeDisabled();
 await page.screenshot({path:'/tmp/git-director-settings-mobile.png',animations:'disabled'});
 expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(390);
 await page.getByRole('tab',{name:'Activity',exact:true}).click();
 await page.getByRole('button',{name:/Beate · codex/}).click();
 await expect(page.getByRole('dialog')).toBeVisible();
 await expect.poll(async()=>Math.round((await page.getByRole('dialog').boundingBox())?.width ?? 0)).toBe(390);
 await expect(page.getByRole('button',{name:'Release registration',exact:true})).toHaveCount(0);
 await page.keyboard.press('Escape');
 await page.route('**/admin/git-director',route=>route.request().headers().accept?.includes('application/json')?route.fulfill({json:{clones:[]}}):route.fallback());
 await page.reload();
 await expect(page.getByText('No active worktrees.')).toBeVisible();
 await page.getByRole('tab',{name:'Merge requests',exact:true}).click();
 await expect(page.getByText('No current merge requests.')).toBeVisible();
 await page.getByRole('tab',{name:'History',exact:true}).click();
 await expect(page.getByText('No history yet.')).toBeVisible();
});
test('registry failures remain visible without blocking settings',async({page})=>{
 await fixture(page);
 await page.route('**/admin/git-director',route=>route.request().headers().accept?.includes('application/json')?route.fulfill({status:403,json:{status:'error',message:'Registry unavailable'}}):route.fallback());
 await page.goto('/admin/git-director');
 await expect(page.getByLabel('Message length')).toBeVisible();
 await page.getByRole('tab',{name:'Activity',exact:true}).click();
 await expect(page.getByRole('alert')).toContainText('Registry unavailable');
 await expect(page.getByText('No active worktrees.')).toHaveCount(0);
});
